# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - run: echo hello

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world

  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: 
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR


workflows:
  # Name the workflow "printing"
  printing:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
<<<<<<< HEAD:.circleci/config.yml
      - build
      
=======
      - build   
      - print_world
>>>>>>> cb6db18d6e7b0e3bec85ad2fa03ae35ad5bbacf3:.circleci/config.yaml
